---
- name: Install and Start nginx
  hosts: all
  become: true
  tasks:
   - name: Install nginx
     apt:
      name: nginx
      state: present
      #shell: apt install nginx   #same as above line
   - name: Start nginx
     service:
      name: nginx
      state: started
